const data = [
  {
    workDate: "2023-12-01",
    overTime: 1,
    lateNightOverTime: 0,
    holidayWorkTime: 0,
    anuualVacation: 0,
    absenteeism: 0,
    publicHolidayTime: 0,
  },
  {
    workDate: "2023-12-02",
    overTime: 1,
    lateNightOverTime: 0,
    holidayWorkTime: 0,
    anuualVacation: 0,
    absenteeism: 0,
    publicHolidayTime: 0,
  },
  {
    workDate: "2023-12-03",
    overTime: 1,
    lateNightOverTime: 0,
    holidayWorkTime: 0,
    anuualVacation: 0,
    absenteeism: 0,
    publicHolidayTime: 0,
  },
  {
    workDate: "2023-12-04",
    overTime: 1,
    lateNightOverTime: 0,
    holidayWorkTime: 0,
    anuualVacation: 0,
    absenteeism: 0,
    publicHolidayTime: 0,
  },
  {
    workDate: "2023-12-05",
    overTime: 1,
    lateNightOverTime: 0,
    holidayWorkTime: 0,
    anuualVacation: 0,
    absenteeism: 0,
    publicHolidayTime: 0,
  },
];
